language: go

go:
- 1.8.x

services:
- docker

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
      $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce

script:
    - make test
    - make build-docker

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - if [ "$TRAVIS_BRANCH" == "master" ]; then make push; fi

notifications:
  email: false

branches:
  only:
  - master
