language: go

go:
    - 1.8.x

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

script: 
    - make test
    - make build-docker

notifications:
  email: false
